language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

# F::Q probably works on 5.8, but some of the tests don't. It's
# disabled for now.
#   - "5.8"

install:

    - cpanm --notest --skip-satisfied Dist::Zilla

    - dzil authordeps         | cpanm --notest --skip-satisfied
    - dzil listdeps --author  | cpanm --notest --skip-satisfied

script:
    - dzil test --all
